[build]
  # Directory to change to before starting a build
  base = "."
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build"
  # Default build command
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # NPM version  
  NPM_VERSION = "8"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "editor"], Country = ["US"]}
  # Don't redirect if the file exists
  force = false

# Specific rules for static assets

[[redirects]]
  from = "/*.png"
  to = "/:splat.png" 
  status = 200
  force = false

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200
  force = false

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = false

# Headers for images
[[headers]]
  for = "/*.{png,jpg,jpeg,gif,svg,ico,webp}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CORS headers for development
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
